pre_bump_hooks = ["cargo fmt", "cargo clippy"]
post_bump_hooks = ["git push", "git push origin v{{version}}"]
tag_prefix = "v"

[commit_types]

[changelog]
path = "CHANGELOG.md"
template = ".changelog_template"
authors = [{ username = "GrayJack", signature = "Eric Shimizu Karbstein" }]

[bump_profiles]
