name: docs
on:
  push:
   branches:
   - dev

jobs:
  rustdoc:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
      CARGO_INCREMENTAL: 0

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: nightly
        components: rust-src

    - name: Cache cargo output
      uses: Swatinem/rust-cache@v1

    - name: Build Rust Documentation
      uses: actions-rs/cargo@v1
      with:
        command: doc
        args: -Zrustdoc-map
      env:
        RUSTDOCFLAGS: --cfg _doc

    - name: Deploy Docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./target/doc
        force_orphan: true
